### ISSUE TITLE
How to: get user to accept cookie policy?

### ISSUE THREAD

**Issue by ajmalafif** [VirtualFox0/gatsby-plugin-google-analytics-gdpr#1]
Hi @VirtualFox0,

Thank you so much for creating this and make it available. I'm not much of a programmer and I get by enough with Gatsby, I want to use this plugin but I'm stuck at figuring out how do I ask my site visitor to accept or reject cookie policy. 

I really appreciate it if there's like a tutorial or something. I know that's a big request of your time and resource, I'm more than happy to contribute any other way so I can to make up to what I am not able to do.

**Comment by VirtualFox0** [comment]
This plugin works in an easy way together with a plugin to show cookie banner generated with CookieHub: [gatsby-plugin-cookiehub-banner](https://github.com/VirtualFox0/gatsby-plugin-cookiehub-banner)
If you don‘t want to use the cookiehub banner service, you have to implement your own banner.
As soon as the user accepts your cookie policy, you can set the cookie `gatsby-plugin-google-analytics-gdpr_cookies-enabled`.

**Comment by ajmalafif** [comment]
I see, it sounds like cookiehub will take care of the banner and once user interacts with it by acecpting the cookie policy, then `gatsby-plugin-google-analytics-gdpr_cookies-enabled`  takes care of it. 

I'll have a look into cookiehub code then. Thanks!
